config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

# Read all
get 'tasks', to: 'tasks#index'
#Read one
# get 'tasks/:id', to: 'tasks#show', as: :task

# CREATE Resto
# First route to get page with form
get 'tasks/new', to: 'tasks#new'
# Second route to post information to
post 'tasks', to: 'tasks#create'

get 'tasks/:id', to: 'tasks#show', as: :task

# UPDATE
# First route to get page with form#
get 'tasks/:id/edit', to: 'tasks#edit', as: :task_edit
# Second route to post information to
# Patch updates a restaurant and does not require you to send all the of parameters related to the object you are updating.
patch 'tasks/:id', to: 'tasks#update'


# DELETE
# One route to delete one restaurant.
delete 'tasks/:id', to: 'tasks#destroy', as: :task_delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>
  <%= t.label :details %>
  <%= t.text_field :details %>
  <%= t.label :completed %>
  <%= t.check_box :completed %>
  <%= t.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<h1> This is our Tasks index page </h1>

<div>
<ul>
<% @tasks.each do |task| %>
<li> <input name="task" type="checkbox" value="" <% "checked" if task.completed %>>
  <%= link_to task.title, task_path(task) %> (Task: <%= task.title %>, Details: <%= task.details %>)-<%= link_to "Update this task",task_edit_path(task) %> -<%= link_to "Delete this task",task_delete_path(task), method: :delete %>
</li>
<% end %>
</div>

<%= link_to "Create a new task", tasks_new_path %>
</ul>

app/views/tasks/new.html.erb
<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<h1> This is info page for <%= @task.title %></h1>

<p> Details: <%= @task.details %></p>
<p> Completed: <%= @task.completed %> </p>
<%= link_to "Update existing task",task_edit_path %>
<%= link_to "Back to index", tasks_path %>
<%= link_to "Delete this task",task_delete_path, method: :delete %>